# Generated by Django 5.1.2 on 2024-10-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AlterModelTable(
            name='opportunity',
            table='newsletter_opportunity',
        ),
    ]
